services:
  - type: web
    name: aparna-property-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    region: oregon
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
